name: RedditBots.Web Deploy

env:
  AZURE_WEBAPP_NAME: redditbots
  CLIENT_APP_LOCATION: ./src/RedditBots.Web/ClientApp
  NODE_VERSION: '14.17.x'     
  DOTNET_VERSION: '5.x'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  deploy_platform:
    if: ${{ github.ref == 'refs/heads/mater' }}
    runs-on: ubuntu-20.04

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # for my future self: az ad sp create-for-rbac --name [name] --sdk-auth

    - name: Azure Deploy
      uses: Azure/cli@1.0.4
      with:
        inlineScript: az deployment sub create
                      --template-file $GITHUB_WORKSPACE/azure-platform/main.bicep
                      --location westeurope
                      --parameters appservicename=${{ env.AZURE_WEBAPP_NAME }} apiKey=${{ secrets.API_SECRET }}
                      --debug
        azcliversion: 2.24.2
        
    - name: Azure Logout
      run: az logout

  build_and_deploy:
     runs-on: ubuntu-20.04

     steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        working-directory: ${{ env.CLIENT_APP_LOCATION }}
        run: npm install

      - name: npm run build
        working-directory: ${{ env.CLIENT_APP_LOCATION }}
        run: npm run build-production

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
      - name: dotnet publish
        run: dotnet publish -c Release -o Release -r win-x64

      - name: Deploy to Azure 
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/mater' }}
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: Release

      - name: Azure Logout
        run: az logout
