name: RedditBots.Web Deploy

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  AZURE_WEBAPP_NAME: redditbots
  CLIENT_APP_LOCATION: ./src/RedditBots.Web/RedditBots.Web/ClientApp
  SERVER_APP_LOCATION: ./src/RedditBots.Web/RedditBots.Web/RedditBots.Web.csproj
  NODE_VERSION: '16.x'     
  DOTNET_VERSION: '7.x'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  deploy_platform_resources:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-20.04

    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        # for future me: az ad sp create-for-rbac --name "{namehere}" --role Contributor --scopes /subscriptions/{subscriptionId} --sdk-auth
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Checkout files
      uses: actions/checkout@main

    - name: Azure deploy
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: westeurope
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: azure-platform/main.bicep
        parameters: projectname=${{ env.AZURE_WEBAPP_NAME }} apiKey=${{ secrets.API_SECRET }}
        
    - name: Azure Logout
      run: az logout

  build_and_deploy:
     runs-on: ubuntu-20.04

     steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Azure Login
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        working-directory: ${{ env.CLIENT_APP_LOCATION }}
        run: npm install

      - name: npm run build
        working-directory: ${{ env.CLIENT_APP_LOCATION }}
        run: npm run build-production

      - name: Setup .NET Core ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet restore
        run: dotnet restore
      - name: dotnet build
        run: dotnet build --configuration Release --no-restore
      - name: dotnet publish
        run: dotnet publish ${{ env.SERVER_APP_LOCATION }} -c Release -o Release -r win-x64 --self-contained true

      - name: Deploy to Azure 
        uses: azure/webapps-deploy@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: Release

      - name: Azure Logout
        if: ${{ github.ref == 'refs/heads/main' }}
        run: az logout
